dist: trusty
language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: source
before_script:
  - 'npm i -g gatsby'
  - 'yarn install'
script:
  - 'npm run test'
after_success:
  - 'yarn run deploy'
